ACTIVIDAD CREACION DE UN DATASET
By KARINA GOMEZ

In [ ]:
# Importar bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Crear un conjunto de datos
value_n_list = ['Andres Gonzalez', 'Pedro Perez', 'John Gomez', 'Maria Lopez', 'Juan Caviedes', 'Diana Arias', 'Tatiana Alvarez', 'Ricardo Lopera', 'Sara Jimenez', 'Samuel Soto']
value_matematicas_list = [4.5, 3.8, 2.0, 4.0, 2.4, 3.2, 4.8, 2.3, 1.2, 3.8]
value_español_list = [3.76, 4.87, 2.69, 3.5, 1.3, 2.8, 4.2, 4.8, 3.7, 3.9]
value_ingles_list = [3.76, 4.87, 2.69, 3.5, 4.2, 4.9, 2.2, 1.2, 4.2, 4.0]

# Crear diccionario de datos
data_dict = {
    "nombre": value_n_list,
    "matematicas": value_matematicas_list,
    "español": value_español_list,
    "ingles": value_ingles_list
}

# Convertir diccionario en DataFrame
df = pd.DataFrame(data_dict)

In [ ]:
df

            nombre  matematicas  español  ingles
0  Andres Gonzalez          4.5     3.76    3.76
1      Pedro Perez          3.8     4.87    4.87
2       John Gomez          2.0     2.69    2.69
3      Maria Lopez          4.0     3.50    3.50
4    Juan Caviedes          2.4     1.30    4.20
5      Diana Arias          3.2     2.80    4.90
6  Tatiana Alvarez          4.8     4.20    2.20
7   Ricardo Lopera          2.3     4.80    1.20
8     Sara Jimenez          1.2     3.70    4.20
9      Samuel Soto          3.8     3.90    4.00

In [ ]:
# Calcular el promedio por fila y crear una nueva columna
df['promedio'] = df[['matematicas', 'español', 'ingles']].mean(axis=1)

# Mostrar el DataFrame resultante
print(df)

            nombre  matematicas  español  ingles  promedio
0  Andres Gonzalez          4.5     3.76    3.76  4.006667
1      Pedro Perez          3.8     4.87    4.87  4.513333
2       John Gomez          2.0     2.69    2.69  2.460000
3      Maria Lopez          4.0     3.50    3.50  3.666667
4    Juan Caviedes          2.4     1.30    4.20  2.633333
5      Diana Arias          3.2     2.80    4.90  3.633333
6  Tatiana Alvarez          4.8     4.20    2.20  3.733333
7   Ricardo Lopera          2.3     4.80    1.20  2.766667
8     Sara Jimenez          1.2     3.70    4.20  3.033333
9      Samuel Soto          3.8     3.90    4.00  3.900000

In [ ]:
df

            nombre  matematicas  español  ingles  promedio
0  Andres Gonzalez          4.5     3.76    3.76  4.006667
1      Pedro Perez          3.8     4.87    4.87  4.513333
2       John Gomez          2.0     2.69    2.69  2.460000
3      Maria Lopez          4.0     3.50    3.50  3.666667
4    Juan Caviedes          2.4     1.30    4.20  2.633333
5      Diana Arias          3.2     2.80    4.90  3.633333
6  Tatiana Alvarez          4.8     4.20    2.20  3.733333
7   Ricardo Lopera          2.3     4.80    1.20  2.766667
8     Sara Jimenez          1.2     3.70    4.20  3.033333
9      Samuel Soto          3.8     3.90    4.00  3.900000

In [ ]:
print(df)

            nombre  matematicas  español  ingles  promedio
0  Andres Gonzalez          4.5     3.76    3.76  4.006667
1      Pedro Perez          3.8     4.87    4.87  4.513333
2       John Gomez          2.0     2.69    2.69  2.460000
3      Maria Lopez          4.0     3.50    3.50  3.666667
4    Juan Caviedes          2.4     1.30    4.20  2.633333
5      Diana Arias          3.2     2.80    4.90  3.633333
6  Tatiana Alvarez          4.8     4.20    2.20  3.733333
7   Ricardo Lopera          2.3     4.80    1.20  2.766667
8     Sara Jimenez          1.2     3.70    4.20  3.033333
9      Samuel Soto          3.8     3.90    4.00  3.900000

In [ ]:
# Definir la función para determinar el nivel académico
def determine_nivel_academico(promedio):
    if 0 <= promedio <= 2.9:
        return "bajo"
    elif 3.0 <= promedio <= 3.9:
        return "medio"
    else:
        return "alto"

# Aplicar la función para crear la nueva columna del nivel academico
df['nivel_academico'] = df['promedio'].apply(determine_nivel_academico)

# Mostrar el DataFrame resultante
print(df)

            nombre  matematicas  español  ingles  promedio nivel_academico
0  Andres Gonzalez          4.5     3.76    3.76  4.006667            alto
1      Pedro Perez          3.8     4.87    4.87  4.513333            alto
2       John Gomez          2.0     2.69    2.69  2.460000            bajo
3      Maria Lopez          4.0     3.50    3.50  3.666667           medio
4    Juan Caviedes          2.4     1.30    4.20  2.633333            bajo
5      Diana Arias          3.2     2.80    4.90  3.633333           medio
6  Tatiana Alvarez          4.8     4.20    2.20  3.733333           medio
7   Ricardo Lopera          2.3     4.80    1.20  2.766667            bajo
8     Sara Jimenez          1.2     3.70    4.20  3.033333           medio
9      Samuel Soto          3.8     3.90    4.00  3.900000           medio

In [ ]:
df = pd.DataFrame(data_dict)
# Usar .describe() para incluir todas las variables
summary = df.describe(include='all')
print(summary)

                 nombre  matematicas    español     ingles
count                10    10.000000  10.000000  10.000000
unique               10          NaN        NaN        NaN
top     Andres Gonzalez          NaN        NaN        NaN
freq                  1          NaN        NaN        NaN
mean                NaN     3.200000   3.552000   3.552000
std                 NaN     1.178511   1.068933   1.189937
min                 NaN     1.200000   1.300000   1.200000
25%                 NaN     2.325000   2.975000   2.892500
50%                 NaN     3.500000   3.730000   3.880000
75%                 NaN     3.950000   4.125000   4.200000
max                 NaN     4.800000   4.870000   4.900000